### PR TITLE
My first branch

### PR DESCRIPTION
**Pull request by Ashnaali3255**

### CODE REVIEW

**Review by joskalenda — COMMENTED** [review]
Hi @Ashnaali3255 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌

> You have submitted a project, that has no pull request, please create one and resubmit your work



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

-----
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._ 🟢

**Comment by Ashnaali3255** [comment]
Hi! @joskalenda What do I have? Please guide me.

**Comment by joskalenda** [comment]
does this pull request contain the project changes you wanted to submit for the review or it is another one?

**Comment by joskalenda** [comment]
@Ashnaali3255 , let's make it simple, you can reopen this closed PR and ask for a review after you have added the PR summary

**Pull request merged**
